# Notes:

# tables for full
samples: samples.csv

experiment_id: dev_TB
date: "2022-06-29"

ref:
  accession: NC_000962.3

tool_params:
  tbprofiler: 
    version: 4.2.0
    caller: "pilon"
  pilon:
    version: 1.23

params:
  trimmomatic:
    trimmer:
      - "LEADING:3"
      - "TRAILING:3"
      - "SLIDINGWINDOW:4:15"
      - "MINLEN:36"

    illumina_clip: data/external/TruSeq3-PE.fa:2:30:10

  # pilon generated VCF filtering
  filtering:
    vcftools: "--remove-filtered Del --remove-filtered LowCov --remove-INFO IMPRECISE --recode -c"

  # snpeff annotation options
  snpeff_opt:
    ann: "-noStats -v -no-downstream -no-upstream"
    ref: Mycobacterium_tuberculosis_h37rv

external:
  ppe_locus_tags: "data/external/H37Rv_PEPPE_locus_tags.txt"
  ppe_locus_coords: "data/external/H37Rv_NC_000962_PEPPE_coords.bed"
